package main

import "metricsrendersender/librehardwaremonitor"

type LibreHardwareMonitorNode = librehardwaremonitor.LibreHardwareMonitorNode
type LibreHardwareMonitorSensorSnapshot = librehardwaremonitor.LibreHardwareMonitorSensorSnapshot
type LibreHardwareMonitorSensorOption = librehardwaremonitor.LibreHardwareMonitorSensorOption
type LibreHardwareMonitorMonitorOption = librehardwaremonitor.LibreHardwareMonitorMonitorOption
type LibreHardwareMonitorData = librehardwaremonitor.LibreHardwareMonitorData
type LibreHardwareMonitorClient = librehardwaremonitor.LibreHardwareMonitorClient

func GetLibreHardwareMonitorClient(url, username, password string) *LibreHardwareMonitorClient {
	return librehardwaremonitor.GetLibreHardwareMonitorClient(url, username, password)
}
